version: "3.2"
services:
  cobudget-api:
    image: greaterthanfinance/cobudget-api:latest
    command: rails s -b 0.0.0.0
    environment:
      - DATABASE_URL=<STAGE_DB>
      - RAILS_ENV=production
      - RACK_ENV=production
      - SECRET_KEY_BASE=<SECRET_KEY_BASE>
      - CANONICAL_HOST=stage.cobudget.co
      - DEVOPS_MAIL=devops@yourdomain.org
      - SMTP_DOMAIN=stage.cobudget.co
      - SMTP_PORT=1025
      - SMTP_SERVER=mailcatcher
  delayed-job:
    image: greaterthanfinance/cobudget-api:latest
    command: rake jobs:work
    environment:
      - DATABASE_URL=<STAGE_DB>
      - RAILS_ENV=production
      - RACK_ENV=production
      - SECRET_KEY_BASE=<SECRET_KEY_BASE>
      - CANONICAL_HOST=stage.cobudget.co
      - DEVOPS_MAIL=devops@yourdomain.org
      - SMTP_DOMAIN=stage.cobudget.co
      - SMTP_PORT=1025
      - SMTP_SERVER=mailcatcher
  activity-emails:
    image: greaterthanfinance/cobudget-api:latest
    command: /bin/bash -c "env >/root/env-vars && cron -f"
    environment:
      - DATABASE_URL=<STAGE_DB>
      - RAILS_ENV=production
      - RACK_ENV=production
      - SECRET_KEY_BASE=<SECRET_KEY_BASE>
      - CANONICAL_HOST=stage.cobudget.co
      - DEVOPS_MAIL=devops@yourdomain.org
      - SMTP_DOMAIN=stage.cobudget.co
      - SMTP_PORT=1025
      - SMTP_SERVER=mailcatcher
  cobudget-ui:
    image: greaterthanfinance/cobudget-ui-stage:latest
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
    environment:
      - DOMAIN=stage.cobudget.co
  mailcatcher:
    image: greaterthanfinance/cobudget-api:latest
    command: mailcatcher --foreground --http-ip 0.0.0.0 --smtp-ip 0.0.0.0
    ports:
      - target: 1080
        published: 1080
