FROM node:6

WORKDIR /app
RUN npm i -g gulp bower gulp-sass && \
    chown -R node:node /app

USER node
COPY package*.json /app/
RUN npm i && \
    cd /app/node_modules && \
    ln -s ../app ./

ARG NODE_ENV
VOLUME [ "/app/node_modules" ]
CMD npm start
