source 'https://rubygems.org'

gem 'rails'
gem 'rails-api'

# crashlogs
gem "sentry-raven"

# payments
gem 'stripe'

# persistance
gem 'pg', '= 0.20.0'

# api
gem 'apipie-rails'
gem 'active_model_serializers', '~> 0.8.0'
gem 'activesupport-json_encoder'
gem 'rack-cors', :require => 'rack/cors'
gem 'responders'

# model utilities
gem 'money-rails'
gem 'groupdate'

# auth
gem 'devise', '3.5.6'
gem 'devise_token_auth',  '0.1.37'
gem 'omniauth'

# server
gem 'puma'
gem 'delayed_job_active_record'

gem 'redcarpet'

group :development, :test do
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'database_cleaner'
  gem 'simplecov', :require => false
  gem 'timecop'
  gem 'faker'
  gem 'factory_girl_rails'
end

ruby "2.4.2"
